<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3 session-form">
            <h2 class="text-center">Index controller</h2>
            <form action="#" method="post">
                <div class="form-group">
                    <input type="text" name="key" class="form-control" id="key" placeholder="Key:">
                </div>
                <div class="form-group">
                    <input type="text" name="value" class="form-control" id="value" placeholder="Value:">
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" class="btn btn-success" value="Submit">
                    <input type="reset" class="btn btn-danger" value="Clear">
                    <a href="list" class="btn btn-primary">List data</a>
                </div>
            </form>
        </div>
    </div>
</div>