<div class="container">
    <div class="row">
        <div class="col-lg-6 session-form">
            <h2 class="text-center">Index controller</h2>
            <form action="">
                <div class="form-group">
                    <input type="text" class="form-control" id="key" placeholder="Key:">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" id="value" placeholder="Value:">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Submit">
                </div>
            </form>
        </div>
        <div class="col-lg-6 session-data">
            <h2 class="text-center">Session data</h2>
        </div>
    </div>
</div>