<div class="container">
    <div class="row">
        <div class="col-lg-offset-3 col-lg-6">
            <h2 class="text-center">List session data</h2>
                <a href="create" class="btn btn-success btn-create-sess">Create new</a>
            <div class="list-session-data">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Key</th>
                            <th>value</th>
                            <th>Operation</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($data as $key => $value): ?>
                        <tr>
                            <td><?=$key;?></td>
                            <td><?=$value;?></td>
                            <td><a href="delete/<?=$key;?>" class="btn btn-danger">Delete</a></td>
                        </tr>
                    <?php endforeach;?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>